import { env } from '@/config/env';
import type { SiteConfig, SocialLink } from '@/types/site';
import type { NavLink } from '@/types/nav';

export const siteConfig: SiteConfig = {
  name: env.siteName,
  // Matches his public LinkedIn headline. His formal HR title at Cateina is
  // Junior Software Developer, so "Senior" here would contradict the first
  // thing a recruiter checks.
  role: 'Full-Stack Engineer',
  discipline: 'Fintech & Open Banking',
  location: 'Mumbai, India',
  email: env.contactEmail,
  phone: env.contactPhone,
  githubUrl: env.githubUrl,
  linkedinUrl: env.linkedinUrl,
  leetcodeUrl: env.leetcodeUrl,
  hackerearthUrl: env.hackerearthUrl,
  hackerrankUrl: env.hackerrankUrl,
  codechefUrl: env.codechefUrl,
  codeforcesUrl: env.codeforcesUrl,
  geeksforgeeksUrl: env.geeksforgeeksUrl,
  kaggleUrl: env.kaggleUrl,
};

export const navLinks: NavLink[] = [
  { id: 'services', label: 'Services', href: '#services' },
  { id: 'work', label: 'Work', href: '#work' },
  { id: 'stack', label: 'Stack', href: '#stack' },
  { id: 'recognition', label: 'Awards', href: '#recognition' },
  { id: 'ai', label: 'AI', href: '#ai' },
  { id: 'experience', label: 'Experience', href: '#experience' },
  // Goes live with the CurrentlyShipping section — see portfolioData.ts.
  // { id: 'now', label: 'Now', href: '#now' },
];

export const socialLinks: SocialLink[] = [
  {
    id: 'github',
    label: 'GitHub',
    handle: '@rohitkum549',
    href: siteConfig.githubUrl,
    icon: 'github',
    category: 'social',
    accentColor: '#2ea44f',
    badge: 'Code & Repos',
  },
  {
    id: 'linkedin',
    label: 'LinkedIn',
    handle: 'in/rohitkumarjha549',
    href: siteConfig.linkedinUrl,
    icon: 'linkedin',
    category: 'social',
    accentColor: '#0a66c2',
    badge: 'Professional',
  },
  {
    id: 'leetcode',
    label: 'LeetCode',
    handle: '@rohitkum549',
    href: siteConfig.leetcodeUrl,
    icon: 'leetcode',
    category: 'coding',
    accentColor: '#ffa116',
    badge: 'Problem Solving',
  },
  {
    id: 'hackerearth',
    label: 'HackerEarth',
    handle: '@rohitkum549',
    href: siteConfig.hackerearthUrl,
    icon: 'hackerearth',
    category: 'competitive',
    accentColor: '#323754',
    badge: 'Contests & Challenges',
  },
  {
    id: 'hackerrank',
    label: 'HackerRank',
    handle: '@rohitkum549',
    href: siteConfig.hackerrankUrl,
    icon: 'hackerrank',
    category: 'coding',
    accentColor: '#2ec4b6',
    badge: 'Certifications & Practice',
  },
  {
    id: 'codechef',
    label: 'CodeChef',
    handle: '@rohitkum549',
    href: siteConfig.codechefUrl,
    icon: 'codechef',
    category: 'competitive',
    accentColor: '#5b4638',
    badge: 'Competitive Programming',
  },
  {
    id: 'codeforces',
    label: 'Codeforces',
    handle: 'rohitkum549',
    href: siteConfig.codeforcesUrl,
    icon: 'codeforces',
    category: 'competitive',
    accentColor: '#1f8acb',
    badge: 'Algorithm Contests',
  },
  {
    id: 'geeksforgeeks',
    label: 'GeeksforGeeks',
    handle: 'rohitkum549',
    href: siteConfig.geeksforgeeksUrl,
    icon: 'geeksforgeeks',
    category: 'coding',
    accentColor: '#2f9d51',
    badge: 'DSA & Tech Concepts',
  },
  {
    id: 'kaggle',
    label: 'Kaggle',
    handle: 'rohitkum549',
    href: siteConfig.kaggleUrl,
    icon: 'kaggle',
    category: 'coding',
    accentColor: '#20beff',
    badge: 'Data Science & AI',
  },
  {
    id: 'phone',
    label: siteConfig.phone,
    href: `tel:${siteConfig.phone.replace(/\s+/g, '')}`,
    icon: 'phone',
    category: 'contact',
    accentColor: '#34d399',
  },
];
